name: Kind Cluster with Korifi

on:
  push

jobs:
  setup-and-install:
    runs-on: ubuntu-latest
    steps:
      # Workaround for https://github.com/nektos/act/issues/107
      - run: sudo id

      - name: Checkout code
        uses: actions/checkout@master
      
      - name: Setup Kind
        uses: engineerd/setup-kind@v0.6.2
        with:
          version: "v0.24.0"
          name: korifi
          config: hack/kind-config.yaml
      
      - name: Validate KinD cluster creation
        run: |
          kubectl cluster-info
          kubectl version
          kubectl get pods -n kube-system
      
      - name: Install Korifi
        run: |
          kubectl apply -f https://github.com/cloudfoundry/korifi/releases/latest/download/install-korifi-kind.yaml

      - name: Verify Korifi Installation
        run: |
          echo "Waiting for all pods to be ready..."

          # while ! [ -n "$(oc get pods -n korifi-installer -l job-name=install-korifi --sort-by=.metadata.creationTimestamp -o jsonpath='{.items[-1:].metadata.name}')" ]; do
          #   echo "Waiting for pod korifi-installer to exist..."
          #   sleep 5
          # done
          kubectl wait --for=jsonpath='{.status.phase}'=Succeeded pod/$(kubectl get pods -n korifi-installer -l job-name=install-korifi --sort-by=.metadata.creationTimestamp -o jsonpath='{.items[-1:].metadata.name}') --timeout=10m -n korifi-installer

          while ! kubectl -n korifi-installer logs job/install-korifi | grep -q "Waiting for the local docker registry to start..."; do
            sleep 5
            echo "retry"
            kubectl get pods --all-namespaces
          done

          # kubectl wait pod --all --for=condition=Ready --all-namespaces --timeout=10m
          # kubectl wait --for=jsonpath='{.status.phase}'=Succeeded pod/$(kubectl get pods -n korifi-installer -l job-name=install-korifi --sort-by=.metadata.creationTimestamp -o jsonpath='{.items[-1:].metadata.name}') --timeout=10m -n korifi-installer
          echo "All pods are ready."
          kubectl get pods --all-namespaces



    # korifi-installer
    # cert-manager
    # local-path-storage
    # kpack
    # project-contour